apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-registry-config
  labels:
    app: nifi-registry
data:
  nifi-registry.properties: |
    nifi.registry.web.http.port=18080

    nifi.registry.db.url=jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
    nifi.registry.db.driver.class=org.postgresql.Driver
    nifi.registry.db.username=${NIFI_REGISTRY_DB_USERNAME}
    nifi.registry.db.password=${NIFI_REGISTRY_DB_PASSWORD}

    nifi.registry.db.max.connections=5
