apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-registry-config
  labels:
{{ include "nifi-registry.labels" . | indent 4 }}
data:
  nifi-registry.properties: |
    nifi.registry.web.http.port=18080

    nifi.registry.db.url={{ .Values.database.url }}
    nifi.registry.db.driver.class=org.postgresql.Driver
    nifi.registry.db.username=${NIFI_REGISTRY_DB_USERNAME}
    nifi.registry.db.password=${NIFI_REGISTRY_DB_PASSWORD}

    nifi.registry.security.needClientAuth=false
