apiVersion: v1
kind: Secret
metadata:
  name: nifi-registry-db
type: Opaque
stringData:
  NIFI_REGISTRY_DB_URL: jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}
  NIFI_REGISTRY_DB_USER: {{ .Values.postgres.user }}
  NIFI_REGISTRY_DB_PASSWORD: {{ .Values.postgres.password }}
  NIFI_REGISTRY_DB_CLASS: org.postgresql.Driver
  NIFI_REGISTRY_FLOW_PROVIDER: database
  NIFI_REGISTRY_DB_DIR: /opt/nifi-drivers
