apiVersion: v1
kind: Secret
metadata:
  name: nifi-registry-db
  labels:
{{ include "nifi-registry.labels" . | indent 4 }}
type: Opaque
stringData:
  NIFI_REGISTRY_DB_USERNAME: {{ .Values.database.username | quote }}
  NIFI_REGISTRY_DB_PASSWORD: {{ .Values.database.password | quote }}
