apiVersion: v1
kind: Secret
metadata:
  name: nifi-registry-db
type: Opaque
stringData:
  NIFI_REGISTRY_DB_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  NIFI_REGISTRY_DB_USER: "{{ .Values.database.user }}"
  NIFI_REGISTRY_DB_PASSWORD: "{{ .Values.database.password }}"
  NIFI_REGISTRY_DB_CLASS: "org.postgresql.Driver"
  NIFI_REGISTRY_FLOW_PROVIDER: "database"
