apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.name" . }}
  labels:
{{ include "nifi-registry.labels" . | indent 4 }}

spec:
  type: ClusterIP
  selector:
{{ include "nifi-registry.selectorLabels" . | indent 4 }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 18080
      protocol: TCP
