apiVersion: v1
kind: Service
metadata:
  name: nifi-registry
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 18080
  selector:
    app: nifi-registry
