image:
  repository: apache/nifi-registry
  tag: 2.6.0

replicaCount: 1

service:
  port: 18080

database:
  host: postgresql.nifi-registry.svc.cluster.local
  port: 5432
  name: nifi_registry
  secretName: nifi-registry-db

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
