image:
  repository: nifi-registry
  tag: 2.6.0-jdbc
  pullPolicy: IfNotPresent

service:
  port: 18080

database:
  url: jdbc:postgresql://postgresql:5432/nifi_registry
  driverClass: org.postgresql.Driver
  username: nifi
  password: nifi

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 2
    memory: 2048Mi

