replicaCount: 1

image:
  repository: apache/nifi-registry
  tag: "2.6.0"
  pullPolicy: IfNotPresent

service:
  port: 18080

database:
  url: jdbc:postgresql://postgresql:5432/nifi_registry
  driverClass: org.postgresql.Driver

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 2
    memory: 2Gi
